ver1:
	gcc DiningProblemVersion1.c -std=c99  -o DiningProblemVersion1.o -lpthread
	./DiningProblemVersion1.o
	rm ./DiningProblemVersion1.o

ver2:
	gcc DiningProblemVersion2.c -std=c99  -o DiningProblemVersion2.o -lpthread
	./DiningProblemVersion2.o > output.txt
	rm ./DiningProblemVersion2.o

analyse:
	python3 AnalyseOutput.py


